### ISSUE TITLE
helping out with the project

### ISSUE THREAD

**Issue by quantfreedom** [murtazayusuf/OrderflowChart#3]
hey this isn't much of an issue but i would like to help out with building on top of this project is possible ... are you working on it often? 

asking also because i am building a backtester and want to be able to work with orderflow data but i need to be able to visualize it like you have done

also the volume profile doesn't seem to line up with the heatmap ... at the point of control of the candle aka the part with teh move volume ... the heatmap color is different from each candle ... really have a lot of questions about the project but really want to help out

**Comment by murtazayusuf** [comment]
Hey sorry for the late reply. Yes I am actually working it's javascript alternative in order to create orderflow footprint charts in realtime. murtazayusufali1@gmail.com is my email. feel free to ping me and we can setup to discuss what ideas you have.
Thanks

**Comment by quantfreedom** [comment]
@murtazayusuf great man ... i just sent you an email ... check that out when you can because i would like to setup a meeting asap

**Comment by murtazayusuf** [comment]
Okay great
